data_source snowflake_db :
    type: snowflake
    connection :
        username: ${SNOWFLAKE_USER}
        password : ${SNOWFLAKE_PASSWORD}
        account : ${SNOWFLAKE_ACCOUNT}
        database : IMDB_ID_MOVIE23_DB
        warehouse : COMPUTE_WH  
        role : ACCOUNTADMIN
        client_session_keep_alive : true
        session_parameters :
            QUERY_TAG : soda-queries
            QUOTED_IDENTIFIERS_IGNORE_CASE : false
        schema : IMDB_ID_MOVIE23_SCHEMA